### ISSUE TITLE
LGPL is Lesser not Library

### ISSUE THREAD

**Issue by mtelka** [rurban/Crypt-OpenSSL-Random#11]
In the `LICENSE` file there is stated:

```
Some other Free Software Foundation software is
covered by the GNU Library General Public License instead.
```

But LGPL is `Lesser General Public License` not `Library General Public License`.  Please see the GPL-2.0 wording at https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

**Comment by rurban** [comment]
This was probably referring to the older LGPL-2
https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html

**Comment by mtelka** [comment]
@rurban would you mind to change it to match the current upstream GPL 2.0 wording?

**Comment by rurban** [comment]
If upstream GPL really changed without a version bump, that would be very unprofessional, but if so, yes

**Comment by mtelka** [comment]
They apparently does so.  It is well known that they retroactively change their (FSF) address when they relocate so it is not surprising they also change some other (hopefully minor) things here and there.

The current GPL 2.0 wording is here: https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

**Comment by rurban** [comment]
Whow, and they didn't even change the date then!

**Comment by mtelka** [comment]
> Whow, and they didn't even change the date then!

Apparently, date is considered non-volatile, since address, etc. does not :-).

**Comment by rurban** [comment]
Care for a PR?
